CLOSE_CONNECTION = "The connection was closed."
DATA_OBTAINED = "Data was obtained successfully for:"
ESTABLISHED_CONNECTION = "Connection established to"
EXECUTING_QUERY = "Executing query: %s"
EXECUTED_QUERY = "Query was executed successfully for:"
INVALID_DATATYPE = "The datatype is not valid"
MISSING_ATTRIBUTES = "Missing attributes."
NO_CONNECTION = "There is no connection."
